@extends('layouts.app')
@section('title','Beranda')
@section('content')
<section class="hero py-5"><div class="container py-4"><div class="row align-items-center g-5"><div class="col-lg-7"><span class="badge rounded-pill text-bg-warning mb-3">Decision Support System</span><h1 class="display-4 fw-bold">Pilih kendaraan dengan kepala dingin.</h1><p class="lead text-white-50">Bandingkan harga, efisiensi, pajak, servis, dan depresiasi dalam satu tampilan yang jernih.</p><div class="d-flex gap-2"><a href="{{ route('search') }}" class="btn btn-warning btn-lg">Mulai mencari <i class="bi bi-arrow-right"></i></a>@guest<a href="{{ route('register') }}" class="btn btn-outline-light btn-lg">Buat akun</a>@endguest</div></div><div class="col-lg-5"><div class="glass rounded-4 p-4"><h5 class="mb-3">Pencarian cepat</h5><form action="{{ route('search') }}" class="row g-3"><div class="col-6"><select name="vehicle_type" class="form-select"><option value="">Semua tipe</option><option value="car">Mobil</option><option value="motorcycle">Motor</option></select></div><div class="col-6"><select name="fuel_type" class="form-select"><option value="">Semua energi</option><option>Bensin</option><option>Diesel</option><option>Hybrid</option><option>Listrik</option></select></div><div class="col-12"><input name="model" class="form-control" placeholder="Model, mis. Avanza atau Beat"></div><div class="col-12"><button class="btn btn-warning w-100"><i class="bi bi-search"></i> Temukan kendaraan</button></div></form></div></div></div></div></section>
<section class="container py-5"><div class="row text-center g-4"><div class="col-md-4"><div class="icon-bubble mb-3"><i class="bi bi-car-front fs-4"></i></div><h2 class="fw-bold">{{ number_format($vehicleCount) }}</h2><p class="text-muted">Kendaraan terverifikasi</p></div><div class="col-md-4"><div class="icon-bubble mb-3"><i class="bi bi-buildings fs-4"></i></div><h2 class="fw-bold">{{ number_format($manufacturerCount) }}</h2><p class="text-muted">Manufacturer mobil & motor</p></div><div class="col-md-4"><div class="icon-bubble mb-3"><i class="bi bi-bar-chart fs-4"></i></div><h2 class="fw-bold">5</h2><p class="text-muted">Dimensi skor ekonomi</p></div></div></section>
<section class="container pb-5"><div class="d-flex justify-content-between align-items-end mb-3"><div><span class="text-ec fw-semibold">KATALOG</span><h2 class="fw-bold">Kendaraan terbaru</h2></div><a href="{{ route('search') }}" class="btn btn-outline-success">Lihat semua</a></div><div class="row g-4">@foreach($latestVehicles as $vehicle)<div class="col-md-6 col-lg-4">@include('partials.vehicle-card')</div>@endforeach</div></section>
<section class="container pb-5"><div class="card bg-ec text-white p-4 p-lg-5"><div class="row align-items-center"><div class="col-lg-8"><h2 class="fw-bold">Bukan sekadar harga paling murah.</h2><p class="mb-lg-0 text-white-50">E-Compare menimbang harga baru, harga bekas, efisiensi, pajak, dan depresiasi untuk rekomendasi yang lebih utuh.</p></div><div class="col-lg-4 text-lg-end"><a href="{{ route('about') }}" class="btn btn-warning">Pelajari metodologi</a></div></div></div></section>
@endsection
@push('styles')<style>@media(max-width:575.98px){.hero .row{--bs-gutter-x:1.5rem}}</style>@endpush
