@extends('layouts.app')
@section('title','Bandingkan Kendaraan')
@section('content')<div class="container py-5"><div class="d-flex justify-content-between align-items-end mb-4"><div><span class="text-ec fw-semibold">DECISION SUPPORT</span><h1 class="fw-bold">Perbandingan Kendaraan</h1><p class="text-muted mb-0">Maksimal tiga kendaraan per perbandingan.</p></div><a href="{{ route('search') }}" class="btn btn-outline-success"><i class="bi bi-plus"></i> Pilih kendaraan</a></div>
@if($vehicles->count()<2)<div class="card p-5 text-center"><i class="bi bi-bar-chart display-3 text-ec"></i><h3 class="mt-3">Pilih setidaknya 2 kendaraan</h3><p class="text-muted">Gunakan halaman pencarian untuk memilih 2–3 kendaraan.</p><a href="{{ route('search') }}" class="btn btn-ec mx-auto">Buka pencarian</a></div>@else
<div class="card overflow-hidden"><div class="table-responsive"><table class="table table-bordered align-middle mb-0"><thead class="table-light"><tr><th style="min-width:180px">Aspek</th>@foreach($vehicles as $v)<th style="min-width:230px"><span class="badge text-bg-success">{{ $v->vehicle_type==='car'?'Mobil':'Motor' }}</span><h5 class="mt-2">{{ $v->display_name }}</h5></th>@endforeach</tr></thead><tbody>
@foreach([['Harga baru','new_price','currency'],['Harga bekas','used_price','currency'],['Efisiensi / EV Range','efficiency_label','text'],['Pajak tahunan','annual_tax','currency'],['Biaya servis','annual_service_cost','currency'],['Depresiasi','depreciation_rate','percent']] as [$label,$field,$format])<tr><th>{{ $label }}</th>@foreach($vehicles as $v)<td>@if($format==='currency')Rp {{ number_format($v->$field,0,',','.') }}@elseif($format==='percent'){{ number_format($v->$field,2,',','.') }}%@else{{ $v->$field }}@endif</td>@endforeach</tr>@endforeach
<tr class="table-success"><th>Economic Score</th>@foreach($vehicles as $v)<td><div class="d-flex align-items-center gap-3"><div class="score-ring" style="--score:{{ $scores[$v->id] }}"><span>{{ number_format($scores[$v->id],1) }}</span></div><strong>{{ $service->category($scores[$v->id]) }}</strong></div></td>@endforeach</tr></tbody></table></div></div>
@php $winner=$vehicles->sortByDesc(fn($v)=>$scores[$v->id])->first(); @endphp<div class="alert alert-success mt-4"><h5><i class="bi bi-trophy-fill text-warning"></i> Rekomendasi: {{ $winner->display_name }}</h5><p class="mb-0">Memiliki Economic Score tertinggi ({{ number_format($scores[$winner->id],2) }}) dalam kelompok ini.</p></div>
<form method="POST" action="{{ route('compare.store') }}" class="card p-4 mt-4">@csrf @foreach($vehicles as $v)<input type="hidden" name="vehicles[]" value="{{ $v->id }}">@endforeach<h4>Simpan perbandingan</h4><div class="row g-3"><div class="col-md-7"><label class="form-label">Nama perbandingan</label><input name="comparison_name" class="form-control" required value="{{ old('comparison_name','Perbandingan '.now()->format('d M Y')) }}"></div><div class="col-md-5"><label class="form-label">Budget (opsional)</label><input name="budget" type="number" class="form-control" min="0" value="{{ old('budget') }}"></div><div class="col-12"><button class="btn btn-ec"><i class="bi bi-save"></i> Simpan ke riwayat</button></div></div></form>@endif</div>@endsection
